### PR TITLE
Solo Newsweeks clone using Bootstrap

### PR DESCRIPTION
**Pull request by ioilmio**
The aim of this project is to get familiar with Bootstrap classes and grid system
to style and display different element on a page.
This is my very first project using it and it was pretty complicated at first but now i feel pretty comfortable using it.

### CODE REVIEW

**Comment by thsvr** [comment]
### **STATUS: CHANGES REQUIRED** :+1: 

Hi @ioilmio :smile_cat: :smile_cat: 
**Your project looks great** :fireworks:  :fireworks: :fireworks: 

To make it perfect, below there are some required changes. Can you please read them carefully, do the changes and then request another review?

Btw, I'm happy to read that you feel comfortable to use it now, I had the same feeling as you when I used it for the first time :smile: 


### **Requested changes:**

:v: Can you please add some padding to the hamburger icon menu, on the navbar, middle and small screens? It looks crashing:






:v: Can you please add some padding around the input and below the button to it looks similar to the original page?








:v: The 3 images on the right column have to be set with the same size, as the original. Can you please fix it?

### **YOURS:**






### **ORIGINAL:**




:v: The footer has to look similar to the original one. For example, the icons should be on the right side, the countries can't be on the same line as the other links, etc.
Can you compare yours and the original and fix it, please?


### **YOURS:**






### **ORIGINAL:**






:v: For the middle and small screens, the text has to be aligned next to the image, on the left side, as the original. Can you please fix it?


### **YOURS:**





### **ORIGINAL:**






:v: For the middle and small screens, the text on this section has to be aligned next to the image, on the left side, as the original. Can you please fix it?

### **YOURS:**






### **ORIGINAL:**



:v: There is an orange x-scroll, on the middle and small screen. Can you fix it?






:v: It is not a good practice to keep commented code. Can you please delete the ones you have (like on line 242 at CSS file, on the line 1411 at HTML file, etc)



:v: Can you please fix the errors on the validator?


01validator




If you have any questions, don't hesitate to contact me through slack @thaís Vieira Azevedo

### **Happy coding and good luck on the next review** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by ioilmio** [comment]
Hello Thais

Thanks for the required changes, I fixed them all. (i think)
The one in the head of HTML is google's normal way to links more fonts with a vertical bar, I split them in two.
i ran the linter, and all comments are deleted, added margin and padding where required, and text is aligned properly now.
Can you check all over again for every screen size, please?

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @ioilmio !
## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### all tasks without [OPTIONAL] tag are REQUIRED.

- [x] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
**add /node_modules to .gitignore**

#### take a look on this screenshots and kindly make the next changes
#### original
Screenshot_2020-03-30 Newsweek
#### yours
Screenshot_2020-03-30 News Week Clone Page

- [x] header should take full width in mobile and medium versions.
- [x] header height size should be bigger(50px)

#### yours
Screenshot_2020-03-30 News Week Clone Page(1)
#### original
Screenshot_2020-03-30 Newsweek(1)

you dit it great with the last changes but you can improve the footer section even more. 
- [x] [OPTIONAL] Change the color of the social media icons(gray)
- [x] Use the right logo for footer
- [ ] [OPTIONAL] separate the footer from the page content(take a look in the gray space betwent the sections)
- [ ] [OPTIONAL] remove the "|" separators in mobile.


- [ ][OPTIONAL] Fix live link in README


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! 👩‍💻

Happy coding 🤓

--Luis Preza

**Comment by ioilmio** [comment]
Hello Luis,
Thank you for the review, I made the required change, hope it will pass now, in case don't hesitate to point me out on some other errors to improve my skills. Thank you again for your time.

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :muscle: 
### Hey @ioilmio    :wave: 
## Good attempts on this one :muscle: :+1: 
But there are some very important things you have to consider before stepping ahead in the issues below :point_down: 
### :one: This page is a clone page from the [newsweek](https://www.newsweek.com/), therefore its section should contain the same order in the different screen sizes 
### :two: Probalbly if you apply max-width you will solve most of the issue in your project

## Here are the issues to address to get the project meet the requirement:wink:

#### Nav Bar

- [x] Navbar should look the same as original, apply some padding to does element.
- [x] Fix Search Bar Input.

##### Required:
Screenshot from 2020-03-30 19-22-42

##### Yours: 
Screenshot from 2020-03-30 19-20-47

---

#### Overall Main Section

- [ ] Set max width to your elements (hint: Body :wink: )
- [x] align your element better

##### Required:
Screenshot from 2020-03-30 19-22-31

##### Yours: 
Screenshot from 2020-03-30 19-21-47

---

#### In The Magazine Section

- [x] wrong aligment 
###### Maybe Both Clear property would help :wink: 
##### Required:
Screenshot from 2020-03-30 19-22-58

##### Yours: 
Screenshot from 2020-03-30 19-22-12

---

#### Footer Section

- [x] wrong aligment
- [x] Logo need changes

###### Maybe Both Clear property would help :wink: 
##### Required:
Screenshot from 2020-03-30 19-23-34

##### Yours: 
Screenshot from 2020-03-30 19-23-23


## Kindly address all these changes and submit a new code review

## Happy coding:computer: 

#### Daniel Laloush

**Comment by serdg0** [comment]
**STATUS: CHANGES REQUIRED.**

Hello [@ioilmio](https://github.com/ioilmio) :v:
You are close to finish! Great job on this one! :tada: 
In this project we should make the newsweek page as exact as possible, so I only 2 things to mentions before we can proceed to approve your project.
Remember, changes marked as [OPTIONAL] are only suggestions to improve your project. This projects will be viewed by potential employers :moneybag: :moneybag:
Here they are:

**Cover**
- [ ] Allignment .- Let's allign this column. (Hint: padding)
cover


**Footer**

- [ ] Allignment .- Let's allign the picture, text and icons.

footer

### [OPTIONAL] **Sidebar**

- [ ] Images .- Text overlapping the images.

sidebar

Kindly address this changed and submit for another code review :smiley: :v:
**Don't hesitate on reaching me in slack for any doubt you may have @sedg**

### Happy coding! :nerd_face: :v:  :computer:

**Review by serdg0 — CHANGES_REQUESTED** [review]
**STATUS: CHANGES REQUIRED.**

Hello [@ioilmio](https://github.com/ioilmio) :v:
You are close to finish! Great job on this one! :tada: 
In this project we should make the newsweek page as exact as possible, so Im only requiring 3 changes before we can proceed to approve your project.
Remember, this projects will be viewed by potential employers :moneybag: :moneybag:
Here they are:

**Cover**
- [x] Allignment .- Let's allign this column. (Hint: padding)
cover


**Footer**

- [x] Allignment .- Let's allign the picture, text and icons.

footer

**Sidebar**

- [x] Images .- Text overlapping the images. 

sidebar

Kindly address this changed and submit for another code review :smiley: :v:
**Don't hesitate on reaching me in slack for any doubt you may have @sedg**

### Happy coding! :nerd_face: :v:  :computer:

**Comment by ioilmio** [comment]
Thank you for your review it was useful and helpful

**Comment by Dandush03** [comment]
### :heavy_check_mark: Project Approve :exploding_head: :checkered_flag:
# Hey @ioilmio   :wave: 
### Great Job so Far :grey_exclamation: :grey_exclamation: :muscle: :smiley: 

### Following Previous Reviews and Seeing you Have Made Required Changes. 
### The project Looks Great.:grey_exclamation::wink:.

## [Optional]
#### Please add a max-width to the whole body, or encapsulate your body in an inner div and set max-width in order that your project would look alike the original
 > if you need any help, let me know through slack

### Good Luck in your Next Assignment
### Happy coding:computer: 
#### Daniel Laloush

**Comment by ioilmio** [comment]
Thank you Daniel for your review and to allow me to progress I added max-width to the main section.
Thanks again to you and all other reviewers

**Pull request merged**
